import os

SUPABASE_URL = "https://TU-PROYECTO.supabase.co"
SUPABASE_KEY = "TU_SERVICE_ROLE_KEY"

CARPETA_OUTLOOK = "FACTURAS"

TEMP_FOLDER = "temp"

LOG_FOLDER = "logs"

ESTADO_FILE = "estado.json"

INTERVALO = 30